apiVersion: v1
kind: Pod
metadata:
  name: example-node-pod
  labels:
    app: webserver
spec:
  containers:
  - name: server
    image: nginx:latest
    resources:
      requests: 
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
