apiVersion: v1
kind: Pod
metadata:
  name: example-node-counter-www
  namespace: example-node-counter
  labels:
    app: example-node-counter
    tier: frontend
spec:
  containers:
  - name: example-node-counter-www
    image: example-node-k8s_www
    imagePullPolicy: Never
    ports:
      - containerPort: 8080
    env:
      - name: VUE_APP_API_ROUTE
        value: "http://$(EXAMPLE_NODE_COUNTER_API_SERVICE_HOST):$(EXAMPLE_NODE_COUNTER_API_SERVICE_PORT)/"